{
  "auth": {
    "oauth2": {
      "scopes": {
        "https://www.googleapis.com/auth/activity": {
          "description": "View the activity history of your Google apps"
        },
        "https://www.googleapis.com/auth/drive": {
          "description": "See, edit, create, and delete all of your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.activity": {
          "description": "View and add to the activity record of files in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive.activity.readonly": {
          "description": "View the activity record of files in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive.appdata": {
          "description": "View and manage its own configuration data in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive.apps.readonly": {
          "description": "View your Google Drive apps"
        },
        "https://www.googleapis.com/auth/drive.file": {
          "description": "View and manage Google Drive files and folders that you have opened or created with this app"
        },
        "https://www.googleapis.com/auth/drive.metadata": {
          "description": "View and manage metadata of files in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive.metadata.readonly": {
          "description": "View metadata for files in your Google Drive"
        },
        "https://www.googleapis.com/auth/drive.photos.readonly": {
          "description": "View the photos, videos and albums in your Google Photos"
        },
        "https://www.googleapis.com/auth/drive.readonly": {
          "description": "See and download all your Google Drive files"
        },
        "https://www.googleapis.com/auth/drive.scripts": {
          "description": "Modify your Google Apps Script scripts' behavior"
        },
        "https://www.googleapis.com/auth/gmail.readonly": {
          "description": "View your email messages and settings"
        }
      }
    }
  },
  "basePath": "/drive/v2.1beta/",
  "baseUrl": "https://www.googleapis.com/drive/v2.1beta/",
  "batchPath": "batch/drive/v2.1beta",
  "description": "Manages files in Drive including uploading, downloading, searching, detecting changes, and updating sharing permissions.",
  "discoveryVersion": "v1",
  "documentationLink": "https://developers.google.com/drive/",
  "etag": "\"-2NioU2H8y8siEzrBOV_qzRI6kQ/Lagqn47DkcdqMIPu3H5Ap0YtEZQ\"",
  "id": "drive:v2.1beta",
  "kind": "discovery#restDescription",
  "name": "drive",
  "ownerDomain": "google.com",
  "ownerName": "Google",
  "protocol": "rest",
  "resources": {
    "about": {
      "methods": {
        "get": {
          "description": "Gets the information about the current user along with Drive API settings",
          "httpMethod": "GET",
          "id": "drive.about.get",
          "path": "about",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        }
      }
    },
    "admin": {
      "resources": {
        "files": {
          "methods": {
            "migrateToTeamDrive": {
              "description": "Migrates a file into a Team Drive. The file and Team Drive must belong to the same Domain, and the requester must be a migration administrator for that domain. The response contains the ID of the migrated file within the Team Drive. If the file is a folder, this ID will be different than the originating ID.",
              "httpMethod": "POST",
              "id": "drive.admin.files.migrateToTeamDrive",
              "path": "admin/files/{fileId}/migrateToTeamDrive",
              "scopes": [
                "https://www.googleapis.com/auth/drive"
              ]
            }
          }
        }
      }
    },
    "approvalevents": {
      "methods": {
        "get": {
          "description": "Gets an ApprovalEvent by ID.",
          "httpMethod": "GET",
          "id": "drive.approvalevents.get",
          "path": "files/{fileId}/approvals/{approvalId}/events/{eventId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "list": {
          "description": "Lists all ApprovalEvents on an Approval.",
          "httpMethod": "GET",
          "id": "drive.approvalevents.list",
          "path": "files/{fileId}/approvals/{approvalId}/events",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        }
      }
    },
    "approvals": {
      "methods": {
        "approve": {
          "description": "DEPRECATED; use drive.approvals.recordDecision instead.",
          "httpMethod": "POST",
          "id": "drive.approvals.approve",
          "path": "files/{fileId}/approvals/{approvalId}/approve",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "cancel": {
          "description": "Cancel an Approval.",
          "httpMethod": "POST",
          "id": "drive.approvals.cancel",
          "path": "files/{fileId}/approvals/{approvalId}/cancel",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "changeReviewers": {
          "description": "Change the reviewers on the Approval.",
          "httpMethod": "POST",
          "id": "drive.approvals.changeReviewers",
          "path": "files/{fileId}/approvals/{approvalId}/changeReviewers",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "comment": {
          "description": "Comment on an Approval.",
          "httpMethod": "POST",
          "id": "drive.approvals.comment",
          "path": "files/{fileId}/approvals/{approvalId}/comment",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "decline": {
          "description": "DEPRECATED; use drive.approvals.recordDecision instead.",
          "httpMethod": "POST",
          "id": "drive.approvals.decline",
          "path": "files/{fileId}/approvals/{approvalId}/decline",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "get": {
          "description": "Gets an Approval by ID.",
          "httpMethod": "GET",
          "id": "drive.approvals.get",
          "path": "files/{fileId}/approvals/{approvalId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "insert": {
          "description": "Inserts a new Approval.",
          "httpMethod": "POST",
          "id": "drive.approvals.insert",
          "path": "files/{fileId}/approvals",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "list": {
          "description": "Lists all approvals on a Drive item.",
          "httpMethod": "GET",
          "id": "drive.approvals.list",
          "path": "files/{fileId}/approvals",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "recordDecision": {
          "description": "Record a decision on an Approval. Only reviewers can make a decision.",
          "httpMethod": "POST",
          "id": "drive.approvals.recordDecision",
          "path": "files/{fileId}/approvals/{approvalId}/recordDecision",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "setDueDate": {
          "description": "Update the Approval's due date. If a date is not specified then any existing due date will be removed.",
          "httpMethod": "POST",
          "id": "drive.approvals.setDueDate",
          "path": "files/{fileId}/approvals/{approvalId}/setDueDate",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        }
      }
    },
    "apps": {
      "methods": {
        "delete": {
          "description": "Uninstall this app.",
          "httpMethod": "DELETE",
          "id": "drive.apps.delete",
          "path": "apps/{appId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "get": {
          "description": "Gets a specific app.",
          "httpMethod": "GET",
          "id": "drive.apps.get",
          "path": "apps/{appId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "insert": {
          "description": "Install this app.",
          "httpMethod": "POST",
          "id": "drive.apps.insert",
          "path": "apps"
        },
        "list": {
          "description": "Lists a user's installed apps.",
          "httpMethod": "GET",
          "id": "drive.apps.list",
          "path": "apps",
          "scopes": [
            "https://www.googleapis.com/auth/drive.apps.readonly"
          ]
        },
        "update": {
          "description": "Update the properties of this app.",
          "httpMethod": "PUT",
          "id": "drive.apps.update",
          "path": "apps/{appId}"
        }
      }
    },
    "attachments": {
      "methods": {
        "insert": {
          "description": "Inserts a gmail attachment into drive.",
          "httpMethod": "POST",
          "id": "drive.attachments.insert",
          "path": "attachments",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/gmail.readonly"
          ]
        }
      }
    },
    "backups": {
      "methods": {
        "delete": {
          "description": "Deletes a backup.",
          "httpMethod": "DELETE",
          "id": "drive.backups.delete",
          "path": "backups/{backupId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata"
          ]
        },
        "get": {
          "description": "Gets a backup's metadata by ID.",
          "httpMethod": "GET",
          "id": "drive.backups.get",
          "path": "backups/{backupId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata"
          ]
        },
        "list": {
          "description": "Lists backups for a user.",
          "httpMethod": "GET",
          "id": "drive.backups.list",
          "path": "backups",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata"
          ]
        },
        "patch": {
          "description": "Updates a backup's metadata.",
          "httpMethod": "PATCH",
          "id": "drive.backups.patch",
          "path": "backups/{backupId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata"
          ]
        },
        "startExtraction": {
          "description": "Starts extracting a backup.",
          "httpMethod": "POST",
          "id": "drive.backups.startExtraction",
          "path": "backups/{backupId}/startExtraction",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata"
          ]
        },
        "stopExtraction": {
          "description": "Stops extraction of a backup.",
          "httpMethod": "POST",
          "id": "drive.backups.stopExtraction",
          "path": "backups/{backupId}/stopExtraction",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata"
          ]
        }
      }
    },
    "changes": {
      "methods": {
        "get": {
          "description": "Deprecated - Use changes.getStartPageToken and changes.list to retrieve recent changes.",
          "httpMethod": "GET",
          "id": "drive.changes.get",
          "path": "changes/{changeId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "getRemainingCount": {
          "description": "Returns the estimated number of change entries that a client could expect by performing a similar changes.list request.",
          "httpMethod": "GET",
          "id": "drive.changes.getRemainingCount",
          "path": "changes/getRemainingCount",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "getStartPageToken": {
          "description": "Gets the starting pageToken for listing future changes.",
          "httpMethod": "GET",
          "id": "drive.changes.getStartPageToken",
          "path": "changes/startPageToken",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "list": {
          "description": "Lists the changes for a user or shared drive.",
          "httpMethod": "GET",
          "id": "drive.changes.list",
          "path": "changes",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "supportsSubscription": true
        },
        "watch": {
          "description": "Subscribe to changes for a user.",
          "httpMethod": "POST",
          "id": "drive.changes.watch",
          "path": "changes/watch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "supportsSubscription": true
        }
      }
    },
    "channels": {
      "methods": {
        "stop": {
          "description": "Stop watching resources through this channel",
          "httpMethod": "POST",
          "id": "drive.channels.stop",
          "path": "channels/stop",
          "scopes": [
            "https://www.googleapis.com/auth/activity",
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.activity",
            "https://www.googleapis.com/auth/drive.activity.readonly",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        }
      }
    },
    "children": {
      "methods": {
        "delete": {
          "description": "Removes a child from a folder.",
          "httpMethod": "DELETE",
          "id": "drive.children.delete",
          "path": "files/{folderId}/children/{childId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "get": {
          "description": "Gets a specific child reference.",
          "httpMethod": "GET",
          "id": "drive.children.get",
          "path": "files/{folderId}/children/{childId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "insert": {
          "description": "Inserts a file into a folder.",
          "httpMethod": "POST",
          "id": "drive.children.insert",
          "path": "files/{folderId}/children",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "list": {
          "description": "Lists a folder's children.",
          "httpMethod": "GET",
          "id": "drive.children.list",
          "path": "files/{folderId}/children",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        }
      }
    },
    "comments": {
      "methods": {
        "delete": {
          "description": "Deletes a comment.",
          "httpMethod": "DELETE",
          "id": "drive.comments.delete",
          "path": "files/{fileId}/comments/{commentId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "get": {
          "description": "Gets a comment by ID.",
          "httpMethod": "GET",
          "id": "drive.comments.get",
          "path": "files/{fileId}/comments/{commentId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "insert": {
          "description": "Creates a new comment on the given file.",
          "httpMethod": "POST",
          "id": "drive.comments.insert",
          "path": "files/{fileId}/comments",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "list": {
          "description": "Lists a file's comments.",
          "httpMethod": "GET",
          "id": "drive.comments.list",
          "path": "files/{fileId}/comments",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "update": {
          "description": "Updates an existing comment.",
          "httpMethod": "PUT",
          "id": "drive.comments.update",
          "path": "files/{fileId}/comments/{commentId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        }
      }
    },
    "drives": {
      "methods": {
        "changeCategoryReferences": {
          "description": "Allows adding, removing, and updating references to Categories on a shared drive.",
          "httpMethod": "POST",
          "id": "drive.drives.changeCategoryReferences",
          "path": "drives/{driveId}/changeCategoryReferences",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "delete": {
          "description": "Permanently deletes a shared drive for which the user is an organizer. The shared drive cannot contain any untrashed items.",
          "httpMethod": "DELETE",
          "id": "drive.drives.delete",
          "path": "drives/{driveId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "get": {
          "description": "Gets a shared drive's metadata by ID.",
          "httpMethod": "GET",
          "id": "drive.drives.get",
          "path": "drives/{driveId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "hide": {
          "description": "Hides a shared drive from the default view.",
          "httpMethod": "POST",
          "id": "drive.drives.hide",
          "path": "drives/{driveId}/hide",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "insert": {
          "description": "Creates a new shared drive.",
          "httpMethod": "POST",
          "id": "drive.drives.insert",
          "path": "drives/{requestId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "list": {
          "description": "Lists the user's shared drives.",
          "httpMethod": "GET",
          "id": "drive.drives.list",
          "path": "drives",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "unhide": {
          "description": "Restores a shared drive to the default view.",
          "httpMethod": "POST",
          "id": "drive.drives.unhide",
          "path": "drives/{driveId}/unhide",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "update": {
          "description": "Updates the metadata for a shared drive.",
          "httpMethod": "PUT",
          "id": "drive.drives.update",
          "path": "drives/{driveId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        }
      }
    },
    "files": {
      "methods": {
        "authorize": {
          "description": "Authorize an app to access a file.",
          "httpMethod": "POST",
          "id": "drive.files.authorize",
          "path": "files/{fileId}/authorize",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "checkPermissions": {
          "description": "Checks for permission fix options for a role, a set of files, and a set of recipients.",
          "httpMethod": "POST",
          "id": "drive.files.checkPermissions",
          "path": "files/checkPermissions",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "copy": {
          "description": "Creates a copy of the specified file.",
          "httpMethod": "POST",
          "id": "drive.files.copy",
          "path": "files/{fileId}/copy",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.photos.readonly"
          ]
        },
        "deauthorize": {
          "description": "Remove an app's authorization from a file.",
          "httpMethod": "POST",
          "id": "drive.files.deauthorize",
          "path": "files/{fileId}/deauthorize",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "delete": {
          "description": "Permanently deletes a file by ID. Skips the trash. The currently authenticated user must own the file or be an organizer on the parent for shared drive files.",
          "httpMethod": "DELETE",
          "id": "drive.files.delete",
          "path": "files/{fileId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "emptyTrash": {
          "description": "Permanently deletes all of the user's trashed files.",
          "httpMethod": "DELETE",
          "id": "drive.files.emptyTrash",
          "path": "files/trash",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "export": {
          "description": "Exports a Google Doc to the requested MIME type and returns the exported content.",
          "httpMethod": "GET",
          "id": "drive.files.export",
          "path": "files/{fileId}/export",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "supportsMediaDownload": true
        },
        "exportGDoc": {
          "description": "Exports a Google Doc to the requested MIME type and returns the exported content. Unlike files.export, this method allows exporting larger content.",
          "httpMethod": "GET",
          "id": "drive.files.exportGDoc",
          "path": "files/{fileId}/exportGDoc",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "supportsMediaDownload": true,
          "useMediaDownloadService": true
        },
        "extract": {
          "description": "Extract the contents of an archive file into Google Drive. Currently supports RAR, TAR/BZ2, TAR/GZIP, and ZIP files.",
          "httpMethod": "POST",
          "id": "drive.files.extract",
          "path": "files/{fileId}/extract",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "extractcancel": {
          "description": "Cancel an archive extraction job by the job ID",
          "httpMethod": "DELETE",
          "id": "drive.files.extractcancel",
          "path": "extractionJobs/{jobId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "extractstatus": {
          "description": "Retrieve the status of an archive extraction job by the job ID",
          "httpMethod": "GET",
          "id": "drive.files.extractstatus",
          "path": "extractionJobs/{jobId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "fixPermissions": {
          "description": "Executes a permission fix option for a role, a set of files, and a set of recipients.",
          "httpMethod": "POST",
          "id": "drive.files.fixPermissions",
          "path": "files/fixPermissions",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "generateCseToken": {
          "description": "Generates a CSE token which can be used to create CSE files.",
          "httpMethod": "GET",
          "id": "drive.files.generateCseToken",
          "path": "files/generateCseToken",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "generateId": {
          "description": "Generates a file ID based on the provided local ID.",
          "httpMethod": "POST",
          "id": "drive.files.generateId",
          "path": "files/generateId",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "generateIds": {
          "description": "Generates a set of file IDs which can be provided in insert or copy requests.",
          "httpMethod": "GET",
          "id": "drive.files.generateIds",
          "path": "files/generateIds",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "get": {
          "description": "Gets a file's metadata by ID.",
          "httpMethod": "GET",
          "id": "drive.files.get",
          "path": "files/{fileId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "supportsMediaDownload": true,
          "supportsSubscription": true,
          "useMediaDownloadService": true
        },
        "insert": {
          "description": "Insert a new file.",
          "httpMethod": "POST",
          "id": "drive.files.insert",
          "path": "files",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ],
          "supportsMediaUpload": true,
          "supportsSubscription": true
        },
        "list": {
          "description": "Lists the user's files.",
          "httpMethod": "GET",
          "id": "drive.files.list",
          "path": "files",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "listCategoryMetadata": {
          "description": "Lists a category metadata on a file.",
          "httpMethod": "GET",
          "id": "drive.files.listCategoryMetadata",
          "path": "files/{fileId}/listCategoryMetadata",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "listLabels": {
          "description": "Lists the labels on a file.",
          "httpMethod": "GET",
          "id": "drive.files.listLabels",
          "path": "files/{fileId}/listLabels",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "migrateToDrivePreFlight": {
          "description": "Verifies if migrating a set of files & folders into a shared drive can succeed without errors. The result is a best effort check on a potential migration.",
          "httpMethod": "POST",
          "id": "drive.files.migrateToDrivePreFlight",
          "path": "admin/files/migrateToDrivePreFlight",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "migrateToTeamDrivePreFlight": {
          "description": "Verifies if migrating a set of files & folders into a Team Drive can succeed without errors. The result is a best effort check on a potential migration.",
          "httpMethod": "POST",
          "id": "drive.files.migrateToTeamDrivePreFlight",
          "path": "admin/files/migrateToTeamDrivePreFlight",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "modifyLabels": {
          "description": "Modifies the set of Labels on a file.",
          "httpMethod": "POST",
          "id": "drive.files.modifyLabels",
          "path": "files/{fileId}/modifyLabels",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ]
        },
        "patch": {
          "description": "Updates file metadata and/or content. This method supports patch semantics.",
          "httpMethod": "PATCH",
          "id": "drive.files.patch",
          "path": "files/{fileId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.scripts"
          ]
        },
        "preview": {
          "description": "Generate a preview for an archive file. Currently supports RAR, TAR/BZ2, TAR/GZIP, and ZIP files.",
          "httpMethod": "GET",
          "id": "drive.files.preview",
          "path": "files/{fileId}/preview",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "remove": {
          "description": "If user owns the file, trashes it; else if parentId is provided, removes the file from that folder; otherwise, unsubscribes the user. This method is unsupported for shared drive files.",
          "httpMethod": "POST",
          "id": "drive.files.remove",
          "path": "files/{fileId}/remove",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "requestAccess": {
          "description": "Deprecated - use drive.files.sendAccessRequest.",
          "httpMethod": "POST",
          "id": "drive.files.requestAccess",
          "path": "files/{fileId}/requestAccess",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "sendAccessRequest": {
          "description": "Requests access to the file for the current user or a list of recipients. A notification is sent to the owner of the file requesting that they share the file with the requesting user or a list of recipients.",
          "httpMethod": "POST",
          "id": "drive.files.sendAccessRequest",
          "path": "files/{fileId}/sendAccessRequest",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "sendShareNotification": {
          "description": "Sends a sharing notification message to one or more users.",
          "httpMethod": "POST",
          "id": "drive.files.sendShareNotification",
          "path": "files/{fileId}/sendShareNotification",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "syncPhotoWithSha1": {
          "description": "Syncs a photo into Google Drive. If the photo already exists in Google Drive, returns the existing File. Otherwise, it syncs the photo and returns the newly synced file.",
          "httpMethod": "POST",
          "id": "drive.files.syncPhotoWithSha1",
          "path": "files/syncPhotoWithSha1",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "touch": {
          "description": "Set the file's updated time to the current server time.",
          "httpMethod": "POST",
          "id": "drive.files.touch",
          "path": "files/{fileId}/touch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ]
        },
        "trash": {
          "description": "Moves a file to the trash. The currently authenticated user must own the file or be at least a fileOrganizer on the parent for shared drive files.",
          "httpMethod": "POST",
          "id": "drive.files.trash",
          "path": "files/{fileId}/trash",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "untrash": {
          "description": "Restores a file from the trash.",
          "httpMethod": "POST",
          "id": "drive.files.untrash",
          "path": "files/{fileId}/untrash",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "update": {
          "description": "Updates file metadata and/or content.",
          "httpMethod": "PUT",
          "id": "drive.files.update",
          "path": "files/{fileId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.scripts"
          ],
          "supportsMediaDownload": true,
          "supportsMediaUpload": true
        },
        "updateCategoryMetadata": {
          "description": "Updates Category Metadata applied to a file. Returns Category Metadata for the Categories that were updated by the request.",
          "httpMethod": "POST",
          "id": "drive.files.updateCategoryMetadata",
          "path": "files/{fileId}/updateCategoryMetadata",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ]
        },
        "watch": {
          "description": "Subscribe to changes on a file",
          "httpMethod": "POST",
          "id": "drive.files.watch",
          "path": "files/{fileId}/watch",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "supportsMediaDownload": true,
          "supportsSubscription": true,
          "useMediaDownloadService": true
        }
      }
    },
    "nextdocpredictions": {
      "methods": {
        "list": {
          "description": "Lists predictions for the documents the user will open.",
          "httpMethod": "GET",
          "id": "drive.nextdocpredictions.list",
          "path": "nextdocpredictions",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        }
      }
    },
    "notifications": {
      "methods": {
        "get": {
          "description": "Gets a notification by ID.",
          "httpMethod": "GET",
          "id": "drive.notifications.get",
          "path": "notifications/{notificationId}",
          "scopes": [
            "https://www.googleapis.com/auth/activity",
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.activity",
            "https://www.googleapis.com/auth/drive.activity.readonly",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "watch": {
          "description": "Subscribe to notifications",
          "httpMethod": "POST",
          "id": "drive.notifications.watch",
          "path": "notifications/watch",
          "scopes": [
            "https://www.googleapis.com/auth/activity",
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.activity",
            "https://www.googleapis.com/auth/drive.activity.readonly",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ],
          "supportsSubscription": true
        }
      }
    },
    "parents": {
      "methods": {
        "delete": {
          "description": "Removes a parent from a file.",
          "httpMethod": "DELETE",
          "id": "drive.parents.delete",
          "path": "files/{fileId}/parents/{parentId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "get": {
          "description": "Gets a specific parent reference.",
          "httpMethod": "GET",
          "id": "drive.parents.get",
          "path": "files/{fileId}/parents/{parentId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "insert": {
          "description": "Adds a parent folder for a file.",
          "httpMethod": "POST",
          "id": "drive.parents.insert",
          "path": "files/{fileId}/parents",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "list": {
          "description": "Lists a file's parents.",
          "httpMethod": "GET",
          "id": "drive.parents.list",
          "path": "files/{fileId}/parents",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        }
      }
    },
    "permissions": {
      "methods": {
        "delete": {
          "description": "Deletes a permission from a file or shared drive.",
          "httpMethod": "DELETE",
          "id": "drive.permissions.delete",
          "path": "files/{fileId}/permissions/{permissionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "get": {
          "description": "Gets a permission by ID.",
          "httpMethod": "GET",
          "id": "drive.permissions.get",
          "path": "files/{fileId}/permissions/{permissionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "getIdForEmail": {
          "description": "Returns the permission ID for an email address.",
          "httpMethod": "GET",
          "id": "drive.permissions.getIdForEmail",
          "path": "permissionIds/{email}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.apps.readonly",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "insert": {
          "description": "Inserts a permission for a file or shared drive.",
          "httpMethod": "POST",
          "id": "drive.permissions.insert",
          "path": "files/{fileId}/permissions",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "list": {
          "description": "Lists a file's or shared drive's permissions.",
          "httpMethod": "GET",
          "id": "drive.permissions.list",
          "path": "files/{fileId}/permissions",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "patch": {
          "description": "Updates a permission using patch semantics.",
          "httpMethod": "PATCH",
          "id": "drive.permissions.patch",
          "path": "files/{fileId}/permissions/{permissionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "update": {
          "description": "Updates a permission.",
          "httpMethod": "PUT",
          "id": "drive.permissions.update",
          "path": "files/{fileId}/permissions/{permissionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        }
      }
    },
    "properties": {
      "methods": {
        "delete": {
          "description": "Deletes a property.",
          "httpMethod": "DELETE",
          "id": "drive.properties.delete",
          "path": "files/{fileId}/properties/{propertyKey}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ]
        },
        "get": {
          "description": "Gets a property by its key.",
          "httpMethod": "GET",
          "id": "drive.properties.get",
          "path": "files/{fileId}/properties/{propertyKey}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "insert": {
          "description": "Adds a property to a file.",
          "httpMethod": "POST",
          "id": "drive.properties.insert",
          "path": "files/{fileId}/properties",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ]
        },
        "list": {
          "description": "Lists a file's properties.",
          "httpMethod": "GET",
          "id": "drive.properties.list",
          "path": "files/{fileId}/properties",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "patch": {
          "description": "Updates a property.",
          "httpMethod": "PATCH",
          "id": "drive.properties.patch",
          "path": "files/{fileId}/properties/{propertyKey}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ]
        },
        "update": {
          "description": "Updates a property.",
          "httpMethod": "PUT",
          "id": "drive.properties.update",
          "path": "files/{fileId}/properties/{propertyKey}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ]
        }
      }
    },
    "replies": {
      "methods": {
        "delete": {
          "description": "Deletes a reply.",
          "httpMethod": "DELETE",
          "id": "drive.replies.delete",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "get": {
          "description": "Gets a reply.",
          "httpMethod": "GET",
          "id": "drive.replies.get",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "insert": {
          "description": "Creates a new reply to the given comment.",
          "httpMethod": "POST",
          "id": "drive.replies.insert",
          "path": "files/{fileId}/comments/{commentId}/replies",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "list": {
          "description": "Lists all of the replies to a comment.",
          "httpMethod": "GET",
          "id": "drive.replies.list",
          "path": "files/{fileId}/comments/{commentId}/replies",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "update": {
          "description": "Updates an existing reply.",
          "httpMethod": "PUT",
          "id": "drive.replies.update",
          "path": "files/{fileId}/comments/{commentId}/replies/{replyId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.file"
          ]
        }
      }
    },
    "revisions": {
      "methods": {
        "delete": {
          "description": "Removes a revision.",
          "httpMethod": "DELETE",
          "id": "drive.revisions.delete",
          "path": "files/{fileId}/revisions/{revisionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ]
        },
        "get": {
          "description": "Gets a specific revision.",
          "httpMethod": "GET",
          "id": "drive.revisions.get",
          "path": "files/{fileId}/revisions/{revisionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "list": {
          "description": "Lists a file's revisions.",
          "httpMethod": "GET",
          "id": "drive.revisions.list",
          "path": "files/{fileId}/revisions",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.photos.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "update": {
          "description": "Updates a revision.",
          "httpMethod": "PUT",
          "id": "drive.revisions.update",
          "path": "files/{fileId}/revisions/{revisionId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file"
          ]
        }
      }
    },
    "settings": {
      "methods": {
        "delete": {
          "description": "Deletes a setting.",
          "httpMethod": "DELETE",
          "id": "drive.settings.delete",
          "path": "settings/{keyname}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ]
        },
        "get": {
          "description": "Gets a setting by its key.",
          "httpMethod": "GET",
          "id": "drive.settings.get",
          "path": "settings/{keyname}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "insert": {
          "description": "Adds a setting for a user.",
          "httpMethod": "POST",
          "id": "drive.settings.insert",
          "path": "settings",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ]
        },
        "list": {
          "description": "Lists a user's settings.",
          "httpMethod": "GET",
          "id": "drive.settings.list",
          "path": "settings",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata",
            "https://www.googleapis.com/auth/drive.metadata.readonly",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "update": {
          "description": "Updates a setting.",
          "httpMethod": "PUT",
          "id": "drive.settings.update",
          "path": "settings/{keyname}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.appdata",
            "https://www.googleapis.com/auth/drive.file",
            "https://www.googleapis.com/auth/drive.metadata"
          ]
        }
      }
    },
    "teamdrives": {
      "methods": {
        "changeCategoryReferences": {
          "description": "Allows adding, removing, and updating references to Categories on a Team Drive.",
          "httpMethod": "POST",
          "id": "drive.teamdrives.changeCategoryReferences",
          "path": "teamdrives/{teamDriveId}/changeCategoryReferences",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "delete": {
          "description": "Permanently deletes a Team Drive for which the user is an organizer. The Team Drive cannot contain any untrashed items.",
          "httpMethod": "DELETE",
          "id": "drive.teamdrives.delete",
          "path": "teamdrives/{teamDriveId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "get": {
          "description": "Gets a Team Drive's metadata by ID.",
          "httpMethod": "GET",
          "id": "drive.teamdrives.get",
          "path": "teamdrives/{teamDriveId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "hide": {
          "description": "Hides a Team Drive from the default view.",
          "httpMethod": "POST",
          "id": "drive.teamdrives.hide",
          "path": "teamdrives/{teamDriveId}/hide",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "insert": {
          "description": "Creates a new Team Drive.",
          "httpMethod": "POST",
          "id": "drive.teamdrives.insert",
          "path": "teamdrives/{requestId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "list": {
          "description": "Lists the user's Team Drives.",
          "httpMethod": "GET",
          "id": "drive.teamdrives.list",
          "path": "teamdrives",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "unhide": {
          "description": "Restores a Team Drive to the default view.",
          "httpMethod": "POST",
          "id": "drive.teamdrives.unhide",
          "path": "teamdrives/{teamDriveId}/unhide",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "update": {
          "description": "Updates a Team Drive's metadata",
          "httpMethod": "PUT",
          "id": "drive.teamdrives.update",
          "path": "teamdrives/{teamDriveId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        }
      }
    },
    "workspaces": {
      "methods": {
        "delete": {
          "description": "Delete the Workspace with the given ID.",
          "httpMethod": "DELETE",
          "id": "drive.workspaces.delete",
          "path": "workspaces/{workspaceId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "get": {
          "description": "Retrieve the metadata of the Workspace with the given ID.",
          "httpMethod": "GET",
          "id": "drive.workspaces.get",
          "path": "workspaces/{workspaceId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "insert": {
          "description": "Inserts a new Workspace.",
          "httpMethod": "POST",
          "id": "drive.workspaces.insert",
          "path": "workspaces",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        },
        "list": {
          "description": "List the user's Workspaces.",
          "httpMethod": "GET",
          "id": "drive.workspaces.list",
          "path": "workspaces",
          "scopes": [
            "https://www.googleapis.com/auth/drive",
            "https://www.googleapis.com/auth/drive.readonly"
          ]
        },
        "update": {
          "description": "Update the metadata of the Workspace with the given ID.",
          "httpMethod": "PUT",
          "id": "drive.workspaces.update",
          "path": "workspaces/{workspaceId}",
          "scopes": [
            "https://www.googleapis.com/auth/drive"
          ]
        }
      }
    }
  },
  "revision": "20200810",
  "rootUrl": "https://www.googleapis.com/",
  "servicePath": "drive/v2.1beta/",
  "title": "Drive API",
  "version": "v2.1beta"
}